CREATE TABLE IF NOT EXISTS RunEvents (
    RunEventId INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId INTEGER NOT NULL,
    Date TEXT NOT NULL,
    Distance INTEGER NOT NULL,
    Effort INTEGER NOT NULL,
    Duration TEXT NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users (UserId)
);