CREATE TABLE IF NOT EXISTS RunEvents (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId INTEGER NOT NULL,
    Date TEXT NOT NULL,
    Distance INTEGER NOT NULL,
    Effort INTEGER NOT NULL,
    Duration TEXT NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users (Id)
);