name: Azure Static Web Apps CI/CD

on:
  workflow_call:
    outputs:
      deploy_url:
        description: 'The URL of the deployed Static Web App'
        value: ${{ jobs.build_and_deploy_job.outputs.deploy_url }}
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      github.event_name == 'workflow_call' ||
      (github.event_name == 'pull_request' && github.event.action != 'closed')
    name: Build and Deploy Job
    outputs:
      deploy_url: ${{ steps.builddeploy.outputs.static_web_app_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Build Blazor WASM
      - name: Publish Blazor WASM
        run: dotnet publish src/Web/Web.csproj -c Release -o build/web

      # Build Azure Function API (isolated worker)
      - name: Publish API
        run: dotnet publish src/Api/Api.csproj -c Release -o build/api

      # Deploy to Azure Static Web Apps
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_RIVER_007F2F303 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "build/web/wwwroot"
          api_location: "build/api"


  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_RIVER_007F2F303 }}
          action: "close"
          app_location: ''
