name: Code Quality Pipeline
on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  call-format:
    name: Code Formatting Compliance Check
    uses: markstanden/coding-standards/.github/workflows/format.yml@ab5f499da58f2e04ee21ec3903b08c1b5e5f033d
    with:
      dotnet-version: "8.0.x"

  call-build:
    name: Build Solution
    uses: markstanden/coding-standards/.github/workflows/build.yml@ab5f499da58f2e04ee21ec3903b08c1b5e5f033d
    needs: call-format
    with:
      dotnet-version: "8.0.x"

  call-unit-tests:
    name: Run Unit Tests
    uses: markstanden/coding-standards/.github/workflows/unit-tests.yml@ab5f499da58f2e04ee21ec3903b08c1b5e5f033d
    needs: call-build
    with:
      dotnet-version: "8.0.x"
      test-filter: "FullyQualifiedName~Unit.Tests"
  
  call-integration-tests:
    name: Run Unit Tests
    uses: markstanden/coding-standards/.github/workflows/integration-tests.yml@ab5f499da58f2e04ee21ec3903b08c1b5e5f033d
    needs: call-build
    with:
      dotnet-version: "8.0.x"
      test-filter: "FullyQualifiedName~Integration.Tests"
