name: Code Quality Pipeline
on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  call-format:
    name: Code Formatting Compliance Check
    uses: markstanden/coding-standards/.github/workflows/format.yml@main
    with:
      dotnet-version: '8.0.x'

  call-build:
    name: Build Solution
    uses: markstanden/coding-standards/.github/workflows/build.yml@main
    needs: call-format
    with:
      dotnet-version: '8.0.x'

  call-unit-tests:
    name: Run Unit Tests
    uses: markstanden/coding-standards/.github/workflows/unit-tests.yml@main
    needs: call-build
    with:
      dotnet-version: '8.0.x'
  
  call-integration-tests:
    name: Run Unit Tests
    uses: markstanden/coding-standards/.github/workflows/integration-tests.yml@main
    needs: call-build
    with:
      dotnet-version: '8.0.x'
